# Generated by Django 5.1.6 on 2025-02-25 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduzca un nombre para su propiedad.', max_length=100)),
                ('descripcion', models.TextField(help_text='Introduzca una descripción para su propiedad.')),
                ('direccion', models.CharField(help_text='Introduzca la dirección de su propiedad.', max_length=255)),
                ('ciudad', models.CharField(help_text='Introduzca la ciudad donde se encuentra su propiedad.', max_length=100)),
                ('estado', models.CharField(blank=True, default=None, help_text='Introduzca el estado donde se encuentra su propiedad.', max_length=100, null=True)),
                ('codigo_postal', models.CharField(help_text='Introduzca un código postal válido de 5 dígitos.', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='El código postal debe tener 5 dígitos.')])),
                ('pais', models.CharField(help_text='Introduzca el país donde se encuentra su propiedad.', max_length=100)),
                ('tipo_de_propiedad', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Villa', 'Villa')], help_text='Seleccione el tipo de propiedad.', max_length=20)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, help_text='Introduzca el precio por noche en EUR.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('disponible_desde', models.DateField(help_text='Introduzca la fecha de inicio de disponibilidad.')),
                ('disponible_hasta', models.DateField(help_text='Introduzca la fecha de fin de disponibilidad.')),
                ('maximo_huespedes', models.PositiveIntegerField(help_text='Introduzca el número máximo de huéspedes permitidos.', validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_de_habitaciones', models.PositiveIntegerField(help_text='Introduzca el número de habitaciones.', validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_de_banos', models.PositiveIntegerField(help_text='Introduzca el número de baños.', validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_de_camas', models.PositiveIntegerField(help_text='Introduzca el número de camas.', validators=[django.core.validators.MinValueValidator(1)])),
                ('tamano', models.PositiveIntegerField(help_text='Introduzca el tamaño en metros cuadrados.', validators=[django.core.validators.MinValueValidator(10)])),
                ('wifi', models.BooleanField(default=False)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('calefaccion', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('mascotas', models.BooleanField(default=False)),
                ('permitido_fumar', models.BooleanField(default=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Introduzca la latitud de su propiedad.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Introduzca la longitud de su propiedad.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('politica_de_cancelacion', models.CharField(choices=[('Flexible', 'Flexible'), ('Moderada', 'Moderada'), ('Estricta', 'Estricta')], help_text='Seleccione la política de cancelación.', max_length=20)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.PositiveIntegerField(help_text='Valoración del 1 al 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario adicional sobre la propiedad.', null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_a_propiedad', to='propiedad.propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_valora', to='usuario.usuario')),
            ],
        ),
    ]
