# Generated by Django 5.1.6 on 2025-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_remove_propiedad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(help_text='Introduzca un nombre para su propiedad.', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='propiedad',
            unique_together={('latitud', 'longitud', 'direccion', 'ciudad', 'pais', 'codigo_postal', 'nombre')},
        ),
    ]
