# Generated by Django 5.1.6 on 2025-02-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_alter_propiedad_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='disponible_desde',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='disponible_hasta',
        ),
        migrations.CreateModel(
            name='FechaBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Introduzca la fecha que desea bloquear.')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_bloqueadas', to='propiedad.propiedad')),
            ],
            options={
                'unique_together': {('propiedad', 'fecha')},
            },
        ),
    ]
