# Generated by Django 5.1.6 on 2025-02-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0004_remove_propiedad_disponible_desde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Seleccione una foto de su propiedad.', upload_to='fotos_propiedades/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='propiedad.propiedad')),
            ],
        ),
    ]
