# Generated by Django 5.1.6 on 2025-02-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0005_fotopropiedad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fotopropiedad',
            unique_together={('propiedad', 'foto')},
        ),
    ]
