# Generated by Django 5.1.6 on 2025-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0006_alter_fotopropiedad_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotopropiedad',
            name='es_portada',
            field=models.BooleanField(default=False, help_text='Seleccione si desea que esta foto sea la portada de su propiedad.'),
        ),
    ]
