# Generated by Django 5.1.6 on 2025-03-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0007_fotopropiedad_es_portada'),
        ('usuario', '0007_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateField(help_text='Introduzca la fecha de llegada.')),
                ('fecha_salida', models.DateField(help_text='Introduzca la fecha de salida.')),
                ('numero_personas', models.PositiveIntegerField(help_text='Introduzca el número de personas.')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, help_text='Introduzca el precio por noche en EUR.', max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Introduzca el precio total en EUR.', max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Cancelada', 'Cancelada')], help_text='Seleccione el estado de la reserva.', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('Transferencia bancaria', 'Transferencia bancaria'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('PayPal', 'PayPal')], help_text='Seleccione el método de pago.', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_usuario', models.TextField(blank=True, help_text='Introduzca un comentario para el anfitrión.', null=True)),
                ('comentarios_anfitrion', models.TextField(blank=True, help_text='Introduzca un comentario para el usuario.', null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='propiedad.propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuario.usuario')),
            ],
            options={
                'ordering': ['fecha_llegada'],
                'unique_together': {('propiedad', 'fecha_llegada', 'fecha_salida')},
            },
        ),
    ]
