# Generated by Django 5.1.6 on 2025-03-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0008_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='comentarios_anfitrion',
        ),
    ]
