# Generated by Django 5.1.6 on 2025-03-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0009_remove_reserva_comentarios_anfitrion'),
        ('usuario', '0009_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='anfitrion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_anfitrion', to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
