# Generated by Django 5.1.6 on 2025-03-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0010_reserva_anfitrion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_aceptacion',
            new_name='fecha_aceptacion_rechazo',
        ),
    ]
