# Generated by Django 5.1.6 on 2025-03-15 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0011_rename_fecha_aceptacion_reserva_fecha_aceptacion_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionpropiedad',
            name='valoracion',
            field=models.FloatField(help_text='Valoración del 1 al 5.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
