# Generated by Django 5.1.6 on 2025-03-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0012_alter_valoracionpropiedad_valoracion'),
        ('usuario', '0010_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracionpropiedad',
            unique_together={('propiedad', 'usuario')},
        ),
    ]
