# Generated by Django 5.1.6 on 2025-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0013_alter_valoracionpropiedad_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionpropiedad',
            name='comentario',
            field=models.TextField(help_text='Comentario adicional sobre la propiedad.'),
        ),
    ]
