# Generated by Django 5.1.6 on 2025-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0014_alter_valoracionpropiedad_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta de crédito', 'Tarjeta de crédito'), ('PayPal', 'PayPal')], help_text='Seleccione el método de pago.', max_length=30),
        ),
    ]
