# Generated by Django 5.1.6 on 2025-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0015_alter_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
