# Generated by Django 5.1.6 on 2025-03-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0016_reserva_payment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propiedad',
            unique_together={('direccion', 'ciudad', 'pais', 'codigo_postal', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='longitud',
        ),
    ]
