# Generated by Django 5.1.6 on 2025-03-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0018_favorito'),
        ('usuario', '0015_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuario.usuario'),
        ),
    ]
