# Generated by Django 5.1.6 on 2025-04-05 14:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0020_alter_favorito_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_especial', models.DecimalField(decimal_places=2, help_text='Precio especial por noche.', max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='propiedad.propiedad')),
            ],
            options={
                'unique_together': {('propiedad', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
