# Generated by Django 5.1.6 on 2025-04-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0022_clickpropiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='propiedad.propiedad'),
        ),
    ]
