# Generated by Django 5.1.6 on 2025-02-08 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='Introduzca su DNI.', max_length=9)),
                ('telefono', models.CharField(help_text='Introduzca su número de teléfono.', max_length=9)),
                ('direccion', models.CharField(help_text='Introduzca su dirección.', max_length=255)),
                ('biografia', models.TextField(blank=True, default=None, help_text='Introduzca una breve descripción sobre usted.', null=True)),
                ('fecha_de_nacimiento', models.DateField(help_text='Introduzca su fecha de nacimiento.')),
                ('rol', models.CharField(choices=[('Anfitrion', 'Anfitrion'), ('Huesped', 'Huesped')], help_text='Seleccione su rol.', max_length=20)),
                ('foto_de_perfil', models.ImageField(blank=True, default=None, help_text='Suba una foto de perfil.', null=True, upload_to='fotos_de_perfil/')),
                ('valoraciones_usuario', models.FloatField(default=0, help_text='Valoración promedio del usuario por sus interacciones.')),
                ('numero_de_resenas', models.PositiveIntegerField(default=0, help_text='Número de valoraciones recibidas por el usuario.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.PositiveIntegerField(help_text='Valoración del 1 al 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario adicional sobre la interacción.', null=True)),
                ('usuario_valorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_a_usuarios', to='usuario.usuario')),
                ('usuario_valorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_valora', to='usuario.usuario')),
            ],
        ),
    ]
