# Generated by Django 5.1.6 on 2025-02-11 12:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(help_text='Introduzca su DNI.', max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(regex='^\\d{8}[A-Za-z]$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(help_text='Introduzca su fecha de nacimiento.', validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2007, 2, 16))]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(help_text='Introduzca su número de teléfono.', max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
