# Generated by Django 5.1.6 on 2025-03-26 10:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracionusuario',
            old_name='usuario_valorador',
            new_name='usuario_que_valora',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero_de_resenas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='valoraciones_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(help_text='Introduzca su fecha de nacimiento.', validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2007, 3, 31))]),
        ),
    ]
