# Generated by Django 5.1.6 on 2025-03-30 09:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_rename_usuario_valorador_valoracionusuario_usuario_que_valora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(help_text='Introduzca su fecha de nacimiento.', validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2007, 4, 4))]),
        ),
    ]
