# Generated by Django 5.1.6 on 2025-04-19 11:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_alter_usuario_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_de_perfil',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_de_nacimiento',
            field=models.DateField(help_text='Introduzca su fecha de nacimiento.', validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2007, 4, 24))]),
        ),
        migrations.DeleteModel(
            name='ValoracionUsuario',
        ),
    ]
