# Generated by Django 5.1.6 on 2025-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
    ]
