# Generated by Django 5.1.6 on 2025-03-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together={('nombre', 'fecha', 'lugar')},
        ),
    ]
