# Generated by Django 5.1.6 on 2025-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_alter_evento_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion_principal',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion_secundaria',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
