name: Django Tests & Codacy Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./marketplace/backend
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        working-directory: ./marketplace/backend
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DB_NAME: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          coverage run manage.py test
          coverage xml
          # Corregir timestamp 
          sed -i "s/timestamp=\"1745166290931\"/timestamp=\"$(date +%s000)\"/g" coverage.xml
      - name: Check for coverage.xml file
        run: |
          ls -la ./marketplace/backend/coverage.xml

      - name: Upload coverage report to Codacy
        working-directory: ./marketplace/backend
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash -s -- -v latest
          # Ejecuta el reporter desde la ruta de caché
          ~/.cache/codacy/coverage-reporter/latest/codacy-coverage-reporter report -l Python -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
